### ISSUE TITLE
Pangolin Error

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Cecret#258]
Hello,

Must be having bad luck today...
I running Cecret version 3.10.20231121, and the pipleline is failing on the Pangolin process, with the following in .commad.err:
```
INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
Traceback (most recent call last):
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/snakemake/__init__.py", line 587, in snakemake
    workflow = Workflow(
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/snakemake/workflow.py", line 242, in __init__
    self.sourcecache = SourceCache()
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/snakemake/sourcecache.py", line 358, in __init__
    os.makedirs(self.cache, exist_ok=True)
  File "/opt/conda/envs/pangolin/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/envs/pangolin/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/envs/pangolin/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/envs/pangolin/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/Users/hottel/.cache'
```

**Comment by erinyoung** [comment]
What version of singularity are you using? I've also observed this with the 4.3.1-pdata-1.23.1 tag.

Can you switch over to using docker?

**Comment by whottel** [comment]
Currently we are using apptainer version 1.2.4-1.el7. Unfortunately, docker is not an option for us as we do not have root access, as our hpc is directly managed by our affiliate university.

**Comment by erinyoung** [comment]
I can't resolve your issue, but I asked pangolin about it and hopefully it will be resolved soon.

Temporary workarounds:
- sent pangolin to false (add `--pangolin false` to your command line) to skip it and then upload the combined fasta file from nextclade on the pangolin website (https://pangolin.cog-uk.io/)
- in a config file, set the pangolin container back to a prior version 4.3.1-pdata-1.23

It'd look something like this:
```
	withName:pangolin{
		container = "staphb/pangolin:4.3.1-pdata-1.23"
	}
```

- change your home directory to be writable by anything/anyone - which I don't actually recommend.

**Comment by whottel** [comment]
Thanks I will look into those options!

**Comment by whottel** [comment]
Hi Erin,

I was able to try a couple different combinations of Cecret and Pango/pdata versions:
[Cecret_tests_summary.xlsx](https://github.com/UPHL-BioNGS/Cecret/files/13492651/Cecret_tests_summary.xlsx)

 It looks like the issue on my end is a change that was was implemented starting with Cecret version  3.10.20231115

**Comment by erinyoung** [comment]
That's awesome! I am not sure why it suddenly started to fail in that version. If it helps any, [3.8.20231031](https://github.com/UPHL-BioNGS/Cecret/releases/tag/3.8.20231031) and forward use the same version of pangolin - so going back to an older workflow will still give you current lineages.

**Comment by erinyoung** [comment]
I think I have some good news. I was working with Curtis (https://github.com/StaPH-B/docker-builds/issues/802) and we think we've resolved the pangolin issue.

The version of Cecret associated with this latest PR (https://github.com/UPHL-BioNGS/Cecret/pull/264) should include the improved docker containers and _should_ resolved your problem.

**Comment by whottel** [comment]
Thanks to you and Curtis for working on this. I just tried version 3.10.20231205 and everything seem to working fine.
